/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.6.1/userguide/multi_project_builds.html in the Gradle documentation.
 */
pluginManagement {
    includeBuild("build-logic")
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
//    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "java-lab"

include("java-basic")

// spring-boot-starter
include("spring-boot-starter")
include("spring-boot-starter:spring-boot-starter-jdbc-demo")
include("dataStructure")
include("library")
include("library:lombokDemo")
include("library:guavaDemo")
include("library:caffeineDemo")
include("library:mapstructDemo")
include("base")
include("dataAccess")
include("dataAccess:sharding")
include("dataAccess:sharding:horizontal-table")

include("dataAccess:jdbc")
include("distribute")
include("infra-redis")
include("infra-rocketmq")
include("infra-redis:jedisDemo")
include("infra-redis:lettuceDemo")
include("infra-redis:jedis-spring-data-redis")
include("infra-redis:lettuce-spring-data-lettuce")
include("infra-redis:redissonDemo")

include("java-basic:newFeature")
include("java-basic:newFeature:8")
include("java-basic:newFeature:21")
include("java-basic:newFeature:9-module-producer")
include("java-basic:newFeature:9-module-consumer")
include("java-basic:foundation")