server:
  port: 8084
spring:
  application:
    name: consumer-service
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: localhost:8848
      discovery:
        enabled: true
        namespace: dev
#      config:
#        namespace: dev
#  config:
#    import:
#      - optional:nacos:infra-nacos.yml?group=INFRA_NACOS_GROUP&refreshEnabled=true