server:
  port: 8081
spring:
  application:
    name: ActuatorApplication
  boot:
    admin:
      client:
        url: http://localhost:18080
        instance:
          name: ${spring.application.name}
management:
  info:
    env:
      enabled: true  # 启用 info 端点读取 info.* 环境属性的功能
    git:
      enabled: true
      mode: full # simple
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        # include 控制的是 HTTP 暴露范围，不代表所有端点都一定能够使用。端点还可能受启用状态、依赖条件、访问控制及安全配置影响
        # include: '*'
        include:
          - health # 检查服务健康状态
          - info # 查看应用信息
          - metrics # 查看可用的监控指标
          - loggers # 查看和修改日志级别
          - mappings # 查看 Spring Web 接口映射
          - threaddump # 获取应用程序当前的 Thread Dump 传统 Java 的 jstack 命令行工具的能力封装成了 HTTP 接口
          - env  # 获取应用程序当前的所有 Environment 属性、配置参数以及 Spring 环境变量
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: Spring Boot Actuator Demo
    version: 1.0.0
    author: jasper