###
GET http://localhost:8082/product/1000


###
POST http://localhost:8082/product
Content-Type: application/json

{
  "name": "test",
  "price": 200,
  "stock": 100
}

###
DELETE http://localhost:8082/product/1000