server:
  port: 8083

spring:
  application:
    name: storage-service
  profiles:
    active: dev
#  config:
#    import: "optional:nacos:storage-service"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#seata:
#  tx-service-group: my_test_tx_group # 事务组
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default      # 事务组对应那个集群
#    grouplist: # nacos registry 这里这样写直接写死
#      default: 127.0.0.1:8091

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl