spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        username: nacos
        password: nacos
#      config:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3307/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: passwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 显式关闭 Docker Compose 自动化，防止它去乱读本地的 compose 文件
  docker:
    compose:
      enabled: false
