spring:
  datasource:
    url: jdbc:mysql://localhost:3307/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: passwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        username: nacos
        password: nacos
#      config:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos
seata:
  enabled: true
  application-id: ${spring.application.name}

  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      dataId: "seata.yml"
      namespace: infra-seata
      group: SEATA_GROUP
      username: 'nacos'
      password: 'nacos'
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      cluster: default
      group: SEATA_GROUP
      username: 'nacos'
      password: 'nacos'


