services:

  mysql-master:
    image: mysql:8.4
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd

    ports:
      - "3309:3306"
    volumes:
      - ./master/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/data:/var/lib/mysql
      - ./master/init:/docker-entrypoint-initdb.d
    networks:
      - mysql-net
  mysql-slave:
    image: mysql:8.4
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "3310:3306"
    depends_on:
      - mysql-master
    volumes:
      - ./slave/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/data:/var/lib/mysql
    networks:
      - mysql-net
networks:
  mysql-net:
